version: '3.4'

services:
  pycon-env:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${PYCON_DOCKER_IMAGE_NAME:-pycon:local}
    network_mode: host
    privileged: true
    working_dir: "${PYCON_WORKING_DIR:-/host/pycon}"
    volumes:
      - ./../:/host/pycon:rw
    user: "${USER_ID}:${GROUP_ID}"
